"""Phase 1C.5: bulk manual upload batches.

Two new tables plus one nullable column on ``telemetry_file``.

``upload_batch`` / ``upload_batch_file`` record a *delivery* - which files an
operator handed over together, and what became of each. They are acquisition
bookkeeping, not an analytical grain: nothing downstream joins through them, and
profiling, quality, coverage and frame reconstruction never see them.

``telemetry_file.upload_batch_id`` is deliberately **nullable**. Files discovered
from a filesystem (and later pulled from RMS) have no batch, and the column exists
only so an uploaded file can be traced back to its delivery. No pipeline stage
branches on it.

Outcome counts are not stored. A batch's completed/failed/duplicate tallies are
derived from its linked files, so a counter cannot drift from the files it
describes. Only ``file_count`` and ``total_bytes`` persist, because they are fixed
at staging time and cannot be re-derived after staged bytes are cleaned up.

Revision ID: 177d94b79149
Revises: c7a4e2b91d38
Create Date: 2026-08-13 00:45:36.498172
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Autogenerate renders the project's custom column type by its fully-qualified
# name, so the module must be imported here or `upgrade()` raises NameError.
import backend.app.db.base

revision: str = '177d94b79149'
down_revision: str | None = 'c7a4e2b91d38'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_batch',
    sa.Column('source_type', sa.Enum('FILESYSTEM', 'MANUAL_UPLOAD', 'RMS', 'SFTP', 'S3', 'AZURE_BLOB', 'API', name='sourcetype', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'UPLOADING', 'REGISTERED', 'PROCESSING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', 'FAILED', name='uploadbatchstatus', native_enum=False, length=48), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('upload_started_at', backend.app.db.base.UtcDateTime(), nullable=True),
    sa.Column('upload_completed_at', backend.app.db.base.UtcDateTime(), nullable=True),
    sa.Column('processing_started_at', backend.app.db.base.UtcDateTime(), nullable=True),
    sa.Column('processing_completed_at', backend.app.db.base.UtcDateTime(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=256), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.app.db.base.UtcDateTime(), nullable=False),
    sa.Column('updated_at', backend.app.db.base.UtcDateTime(), nullable=False),
    sa.CheckConstraint('file_count >= 0', name=op.f('ck_upload_batch_file_count_non_negative')),
    sa.CheckConstraint('total_bytes >= 0', name=op.f('ck_upload_batch_total_bytes_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_batch'))
    )
    with op.batch_alter_table('upload_batch', schema=None) as batch_op:
        batch_op.create_index('ix_upload_batch_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_upload_batch_status', ['status'], unique=False)

    op.create_table('upload_batch_file',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('staged_reference', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REGISTERED', 'DUPLICATE', 'REJECTED', 'FAILED', name='uploadfilestatus', native_enum=False, length=48), nullable=False),
    sa.Column('telemetry_file_id', sa.Uuid(), nullable=True),
    sa.Column('duplicate_of_file_id', sa.Uuid(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('staged_at', backend.app.db.base.UtcDateTime(), nullable=False),
    sa.Column('registered_at', backend.app.db.base.UtcDateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_upload_batch_file_size_bytes_non_negative')),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batch.id'], name=op.f('fk_upload_batch_file_batch_id_upload_batch'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['duplicate_of_file_id'], ['telemetry_file.id'], name=op.f('fk_upload_batch_file_duplicate_of_file_id_telemetry_file'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['telemetry_file_id'], ['telemetry_file.id'], name=op.f('fk_upload_batch_file_telemetry_file_id_telemetry_file'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_batch_file')),
    sa.UniqueConstraint('batch_id', 'original_filename', name='uq_upload_batch_file_identity')
    )
    with op.batch_alter_table('upload_batch_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_batch_file_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index('ix_upload_batch_file_sha256', ['sha256'], unique=False)
        batch_op.create_index('ix_upload_batch_file_status', ['status'], unique=False)

    with op.batch_alter_table('telemetry_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_batch_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_telemetry_file_upload_batch_id'), ['upload_batch_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_telemetry_file_upload_batch_id_upload_batch'), 'upload_batch', ['upload_batch_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry_file', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_telemetry_file_upload_batch_id_upload_batch'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_telemetry_file_upload_batch_id'))
        batch_op.drop_column('upload_batch_id')

    with op.batch_alter_table('upload_batch_file', schema=None) as batch_op:
        batch_op.drop_index('ix_upload_batch_file_status')
        batch_op.drop_index('ix_upload_batch_file_sha256')
        batch_op.drop_index(batch_op.f('ix_upload_batch_file_batch_id'))

    op.drop_table('upload_batch_file')
    with op.batch_alter_table('upload_batch', schema=None) as batch_op:
        batch_op.drop_index('ix_upload_batch_status')
        batch_op.drop_index('ix_upload_batch_created_at')

    op.drop_table('upload_batch')
    # ### end Alembic commands ###
