"""add_discrete_event_tables

Revision ID: 56379df29815
Revises: 84fce8cc3d03
Create Date: 2026-09-17 12:19:21.576908
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
import backend.app.db.base
revision: str = '56379df29815'
down_revision: str | None = '84fce8cc3d03'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_event',
    sa.Column('charger_id', sa.String(length=128), nullable=False),
    sa.Column('component_type', sa.String(length=64), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('alarm_code', sa.String(length=128), nullable=False),
    sa.Column('alarm_name', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'MAJOR', 'MINOR', 'WARNING', 'INFO', name='alarmseverity', native_enum=False, length=48), nullable=False),
    sa.Column('start_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('end_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('start_state', sa.String(length=255), nullable=True),
    sa.Column('end_state', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='eventconfidence', native_enum=False, length=48), nullable=False),
    sa.Column('has_gap', sa.Boolean(), nullable=False),
    sa.Column('quality_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reconstruction_version', sa.String(length=32), nullable=False),
    sa.Column('source_first_frame_id', sa.Uuid(), nullable=True),
    sa.Column('source_last_frame_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alarm_event')),
    sa.UniqueConstraint('charger_id', 'alarm_code', 'component_type', 'component_id', 'start_time', 'reconstruction_version', name='uq_alarm_event')
    )
    op.create_index(op.f('ix_alarm_event_alarm_code'), 'alarm_event', ['alarm_code'], unique=False)
    op.create_index(op.f('ix_alarm_event_charger_id'), 'alarm_event', ['charger_id'], unique=False)
    op.create_index(op.f('ix_alarm_event_end_time'), 'alarm_event', ['end_time'], unique=False)
    op.create_index(op.f('ix_alarm_event_is_open'), 'alarm_event', ['is_open'], unique=False)
    op.create_index('ix_alarm_event_lookup', 'alarm_event', ['charger_id', 'alarm_code', 'start_time'], unique=False)
    op.create_index('ix_alarm_event_open', 'alarm_event', ['charger_id', 'is_open'], unique=False)
    op.create_index(op.f('ix_alarm_event_start_time'), 'alarm_event', ['start_time'], unique=False)
    op.create_table('charging_session_event',
    sa.Column('charger_id', sa.String(length=128), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('start_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('charging_start_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('charging_end_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('end_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('energy_delivered_kwh', sa.Float(), nullable=True),
    sa.Column('start_soc', sa.Float(), nullable=True),
    sa.Column('end_soc', sa.Float(), nullable=True),
    sa.Column('stop_reason', sa.String(length=255), nullable=True),
    sa.Column('termination_class', sa.Enum('NORMAL', 'USER_STOPPED', 'REMOTE_STOPPED', 'FAULT_STOPPED', 'EMERGENCY_STOPPED', 'COMMUNICATION_LOST', 'INCOMPLETE', 'UNKNOWN', name='terminationclass', native_enum=False, length=48), nullable=True),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='eventconfidence', native_enum=False, length=48), nullable=False),
    sa.Column('has_gap', sa.Boolean(), nullable=False),
    sa.Column('quality_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reconstruction_version', sa.String(length=32), nullable=False),
    sa.Column('source_first_frame_id', sa.Uuid(), nullable=True),
    sa.Column('source_last_frame_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_charging_session_event')),
    sa.UniqueConstraint('charger_id', 'connector_id', 'start_time', 'reconstruction_version', name='uq_charging_session_event')
    )
    op.create_index(op.f('ix_charging_session_event_charger_id'), 'charging_session_event', ['charger_id'], unique=False)
    op.create_index(op.f('ix_charging_session_event_connector_id'), 'charging_session_event', ['connector_id'], unique=False)
    op.create_index(op.f('ix_charging_session_event_end_time'), 'charging_session_event', ['end_time'], unique=False)
    op.create_index('ix_charging_session_event_lookup', 'charging_session_event', ['charger_id', 'connector_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_charging_session_event_session_id'), 'charging_session_event', ['session_id'], unique=False)
    op.create_index(op.f('ix_charging_session_event_start_time'), 'charging_session_event', ['start_time'], unique=False)
    op.create_index('ix_charging_session_event_time', 'charging_session_event', ['charger_id', 'start_time'], unique=False)
    op.create_table('configuration_change_event',
    sa.Column('charger_id', sa.String(length=128), nullable=False),
    sa.Column('change_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('old_config_hash', sa.String(length=64), nullable=False),
    sa.Column('new_config_hash', sa.String(length=64), nullable=False),
    sa.Column('changed_fields_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('previous_config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('new_config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reconstruction_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuration_change_event')),
    sa.UniqueConstraint('charger_id', 'old_config_hash', 'new_config_hash', 'change_time', 'reconstruction_version', name='uq_configuration_change_event')
    )
    op.create_index(op.f('ix_configuration_change_event_change_time'), 'configuration_change_event', ['change_time'], unique=False)
    op.create_index(op.f('ix_configuration_change_event_charger_id'), 'configuration_change_event', ['charger_id'], unique=False)
    op.create_index('ix_configuration_change_event_lookup', 'configuration_change_event', ['charger_id', 'change_time'], unique=False)
    op.create_index(op.f('ix_configuration_change_event_new_config_hash'), 'configuration_change_event', ['new_config_hash'], unique=False)
    op.create_index(op.f('ix_configuration_change_event_old_config_hash'), 'configuration_change_event', ['old_config_hash'], unique=False)
    op.create_table('fault_event',
    sa.Column('charger_id', sa.String(length=128), nullable=False),
    sa.Column('component_type', sa.String(length=64), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('fault_code', sa.String(length=128), nullable=False),
    sa.Column('fault_name', sa.String(length=255), nullable=False),
    sa.Column('start_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('end_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('initial_reading', sa.String(length=255), nullable=True),
    sa.Column('clearing_reading', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='eventconfidence', native_enum=False, length=48), nullable=False),
    sa.Column('has_gap', sa.Boolean(), nullable=False),
    sa.Column('quality_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reconstruction_version', sa.String(length=32), nullable=False),
    sa.Column('source_first_frame_id', sa.Uuid(), nullable=True),
    sa.Column('source_last_frame_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fault_event')),
    sa.UniqueConstraint('charger_id', 'fault_code', 'component_type', 'component_id', 'start_time', 'reconstruction_version', name='uq_fault_event')
    )
    op.create_index(op.f('ix_fault_event_charger_id'), 'fault_event', ['charger_id'], unique=False)
    op.create_index(op.f('ix_fault_event_end_time'), 'fault_event', ['end_time'], unique=False)
    op.create_index(op.f('ix_fault_event_fault_code'), 'fault_event', ['fault_code'], unique=False)
    op.create_index(op.f('ix_fault_event_is_open'), 'fault_event', ['is_open'], unique=False)
    op.create_index('ix_fault_event_lookup', 'fault_event', ['charger_id', 'fault_code', 'start_time'], unique=False)
    op.create_index(op.f('ix_fault_event_start_time'), 'fault_event', ['start_time'], unique=False)
    op.create_table('state_transition_event',
    sa.Column('charger_id', sa.String(length=128), nullable=False),
    sa.Column('component_type', sa.String(length=64), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('state_field', sa.String(length=128), nullable=False),
    sa.Column('from_state', sa.String(length=255), nullable=True),
    sa.Column('to_state', sa.String(length=255), nullable=False),
    sa.Column('transition_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('frame_sequence', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_state_transition_event')),
    sa.UniqueConstraint('charger_id', 'component_type', 'component_id', 'state_field', 'transition_time', 'frame_sequence', name='uq_state_transition_event')
    )
    op.create_index(op.f('ix_state_transition_event_charger_id'), 'state_transition_event', ['charger_id'], unique=False)
    op.create_index('ix_state_transition_event_lookup', 'state_transition_event', ['charger_id', 'state_field', 'transition_time'], unique=False)
    op.create_index(op.f('ix_state_transition_event_state_field'), 'state_transition_event', ['state_field'], unique=False)
    op.create_index(op.f('ix_state_transition_event_transition_time'), 'state_transition_event', ['transition_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_state_transition_event_transition_time'), table_name='state_transition_event')
    op.drop_index(op.f('ix_state_transition_event_state_field'), table_name='state_transition_event')
    op.drop_index('ix_state_transition_event_lookup', table_name='state_transition_event')
    op.drop_index(op.f('ix_state_transition_event_charger_id'), table_name='state_transition_event')
    op.drop_table('state_transition_event')
    op.drop_index(op.f('ix_fault_event_start_time'), table_name='fault_event')
    op.drop_index('ix_fault_event_lookup', table_name='fault_event')
    op.drop_index(op.f('ix_fault_event_is_open'), table_name='fault_event')
    op.drop_index(op.f('ix_fault_event_fault_code'), table_name='fault_event')
    op.drop_index(op.f('ix_fault_event_end_time'), table_name='fault_event')
    op.drop_index(op.f('ix_fault_event_charger_id'), table_name='fault_event')
    op.drop_table('fault_event')
    op.drop_index(op.f('ix_configuration_change_event_old_config_hash'), table_name='configuration_change_event')
    op.drop_index(op.f('ix_configuration_change_event_new_config_hash'), table_name='configuration_change_event')
    op.drop_index('ix_configuration_change_event_lookup', table_name='configuration_change_event')
    op.drop_index(op.f('ix_configuration_change_event_charger_id'), table_name='configuration_change_event')
    op.drop_index(op.f('ix_configuration_change_event_change_time'), table_name='configuration_change_event')
    op.drop_table('configuration_change_event')
    op.drop_index('ix_charging_session_event_time', table_name='charging_session_event')
    op.drop_index(op.f('ix_charging_session_event_start_time'), table_name='charging_session_event')
    op.drop_index(op.f('ix_charging_session_event_session_id'), table_name='charging_session_event')
    op.drop_index('ix_charging_session_event_lookup', table_name='charging_session_event')
    op.drop_index(op.f('ix_charging_session_event_end_time'), table_name='charging_session_event')
    op.drop_index(op.f('ix_charging_session_event_connector_id'), table_name='charging_session_event')
    op.drop_index(op.f('ix_charging_session_event_charger_id'), table_name='charging_session_event')
    op.drop_table('charging_session_event')
    op.drop_index(op.f('ix_alarm_event_start_time'), table_name='alarm_event')
    op.drop_index('ix_alarm_event_open', table_name='alarm_event')
    op.drop_index('ix_alarm_event_lookup', table_name='alarm_event')
    op.drop_index(op.f('ix_alarm_event_is_open'), table_name='alarm_event')
    op.drop_index(op.f('ix_alarm_event_end_time'), table_name='alarm_event')
    op.drop_index(op.f('ix_alarm_event_charger_id'), table_name='alarm_event')
    op.drop_index(op.f('ix_alarm_event_alarm_code'), table_name='alarm_event')
    op.drop_table('alarm_event')
    # ### end Alembic commands ###
