"""add_silver_telemetry_tables

Revision ID: 84fce8cc3d03
Revises: 177d94b79149
Create Date: 2026-09-17 10:51:31.795931
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
import backend.app.db.base
revision: str = '84fce8cc3d03'
down_revision: str | None = '177d94b79149'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('silver_alarm_observation',
    sa.Column('charger_id', sa.String(length=128), nullable=False),
    sa.Column('event_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('frame_sequence', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Uuid(), nullable=False),
    sa.Column('active_alarms_count', sa.Integer(), nullable=False),
    sa.Column('active_alarm_codes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ground_resistance_value', sa.Float(), nullable=True),
    sa.Column('rtc_clock_drift_warning', sa.String(length=255), nullable=True),
    sa.Column('rms_disabled_alarm', sa.String(length=255), nullable=True),
    sa.Column('grid_fail', sa.String(length=255), nullable=True),
    sa.Column('class_c_spd_fail', sa.String(length=255), nullable=True),
    sa.Column('ne_voltage_high_alarm', sa.String(length=255), nullable=True),
    sa.Column('line_1_fail', sa.String(length=255), nullable=True),
    sa.Column('line_2_fail', sa.String(length=255), nullable=True),
    sa.Column('line_3_fail', sa.String(length=255), nullable=True),
    sa.Column('door_open', sa.String(length=255), nullable=True),
    sa.Column('smoke_alarm', sa.String(length=255), nullable=True),
    sa.Column('emergency_stop_active', sa.String(length=255), nullable=True),
    sa.Column('system_fan_fail', sa.String(length=255), nullable=True),
    sa.Column('filter_maintenance_warning', sa.String(length=255), nullable=True),
    sa.Column('grid_abnormal', sa.String(length=255), nullable=True),
    sa.Column('sd_card_fail', sa.String(length=255), nullable=True),
    sa.Column('sd_card_crc_fail', sa.String(length=255), nullable=True),
    sa.Column('input_rcbo_tripped', sa.String(length=255), nullable=True),
    sa.Column('mccb_tripped', sa.String(length=255), nullable=True),
    sa.Column('class_d_spd_fail_alarm', sa.String(length=255), nullable=True),
    sa.Column('ground_fault_alarm', sa.String(length=255), nullable=True),
    sa.Column('hvlv_cut_off_alarm', sa.String(length=255), nullable=True),
    sa.Column('auxillary_mcb_trip_alarm', sa.String(length=255), nullable=True),
    sa.Column('backup_battery_low', sa.String(length=255), nullable=True),
    sa.Column('earth_leakage_sensed_alarm', sa.String(length=255), nullable=True),
    sa.Column('short_circuit', sa.String(length=255), nullable=True),
    sa.Column('last_insulation_test_fail', sa.String(length=255), nullable=True),
    sa.Column('fuse_fail_alarm', sa.String(length=255), nullable=True),
    sa.Column('ac_fail_alarm', sa.String(length=255), nullable=True),
    sa.Column('dc_positive_insulation_resistance', sa.Float(), nullable=True),
    sa.Column('dc_negative_insulation_resistance', sa.Float(), nullable=True),
    sa.Column('last_insulation_test_status', sa.String(length=255), nullable=True),
    sa.Column('calculated_insulation_resistance', sa.Float(), nullable=True),
    sa.Column('mdl_fault', sa.String(length=255), nullable=True),
    sa.Column('fan_fault', sa.String(length=255), nullable=True),
    sa.Column('dcdc_eeprom_faults', sa.String(length=255), nullable=True),
    sa.Column('fan_1_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_2_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_3_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_4_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_5_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_6_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_7_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_8_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_9_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_10_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_11_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_12_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_13_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_14_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_15_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_16_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_17_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_18_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_19_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_20_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_21_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_22_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_23_fail', sa.String(length=255), nullable=True),
    sa.Column('dc_section_fan_fail', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['telemetry_source_frame.id'], name=op.f('fk_silver_alarm_observation_frame_id_telemetry_source_frame'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_silver_alarm_observation')),
    sa.UniqueConstraint('charger_id', 'event_time', 'frame_sequence', name='uq_silver_alarm_observation')
    )
    op.create_index(op.f('ix_silver_alarm_observation_charger_id'), 'silver_alarm_observation', ['charger_id'], unique=False)
    op.create_index(op.f('ix_silver_alarm_observation_event_time'), 'silver_alarm_observation', ['event_time'], unique=False)
    op.create_index(op.f('ix_silver_alarm_observation_frame_id'), 'silver_alarm_observation', ['frame_id'], unique=False)
    op.create_index('ix_silver_alarm_observation_lookup', 'silver_alarm_observation', ['charger_id', 'event_time', 'frame_sequence'], unique=False)
    op.create_table('silver_charger_telemetry',
    sa.Column('charger_id', sa.String(length=128), nullable=False),
    sa.Column('event_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('frame_sequence', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Uuid(), nullable=False),
    sa.Column('ocpp_id', sa.String(length=128), nullable=True),
    sa.Column('l1_n_voltage', sa.Float(), nullable=True),
    sa.Column('l2_n_voltage', sa.Float(), nullable=True),
    sa.Column('l3_n_voltage', sa.Float(), nullable=True),
    sa.Column('neutral_voltage', sa.Float(), nullable=True),
    sa.Column('line_1_input_current', sa.Float(), nullable=True),
    sa.Column('line_2_input_current', sa.Float(), nullable=True),
    sa.Column('line_3_input_current', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('power_factor', sa.Float(), nullable=True),
    sa.Column('active_power', sa.Float(), nullable=True),
    sa.Column('l1_l2_voltage', sa.Float(), nullable=True),
    sa.Column('l2_l3_voltage', sa.Float(), nullable=True),
    sa.Column('l3_l1_voltage', sa.Float(), nullable=True),
    sa.Column('reactive_power', sa.Float(), nullable=True),
    sa.Column('active_energy', sa.Float(), nullable=True),
    sa.Column('reactive_energy', sa.Float(), nullable=True),
    sa.Column('apparent_energy', sa.Float(), nullable=True),
    sa.Column('l1_n_voltage_meter', sa.Float(), nullable=True),
    sa.Column('l2_n_voltage_meter', sa.Float(), nullable=True),
    sa.Column('l3_n_voltage_meter', sa.Float(), nullable=True),
    sa.Column('grid_status', sa.String(length=255), nullable=True),
    sa.Column('apparent_power', sa.Float(), nullable=True),
    sa.Column('pilot_upper_tcp_interface', sa.String(length=255), nullable=True),
    sa.Column('rms_enable_modified_by', sa.String(length=255), nullable=True),
    sa.Column('fan_run_status', sa.String(length=255), nullable=True),
    sa.Column('fan_set_speed', sa.Float(), nullable=True),
    sa.Column('system_fan_speed', sa.Float(), nullable=True),
    sa.Column('cabinet_temperature', sa.Float(), nullable=True),
    sa.Column('cooling_temp_sensor_1', sa.Float(), nullable=True),
    sa.Column('cooling_temp_sensor_2', sa.Float(), nullable=True),
    sa.Column('fan_card_status', sa.String(length=255), nullable=True),
    sa.Column('fan_1_status', sa.String(length=255), nullable=True),
    sa.Column('fan_2_status', sa.String(length=255), nullable=True),
    sa.Column('fan_3_status', sa.String(length=255), nullable=True),
    sa.Column('fan_4_status', sa.String(length=255), nullable=True),
    sa.Column('fan_5_status', sa.String(length=255), nullable=True),
    sa.Column('fan_6_status', sa.String(length=255), nullable=True),
    sa.Column('fan_7_status', sa.String(length=255), nullable=True),
    sa.Column('fan_8_status', sa.String(length=255), nullable=True),
    sa.Column('fan_9_status', sa.String(length=255), nullable=True),
    sa.Column('fan_10_status', sa.String(length=255), nullable=True),
    sa.Column('fan_11_status', sa.String(length=255), nullable=True),
    sa.Column('fan_12_status', sa.String(length=255), nullable=True),
    sa.Column('fan_13_status', sa.String(length=255), nullable=True),
    sa.Column('fan_14_status', sa.String(length=255), nullable=True),
    sa.Column('fan_15_status', sa.String(length=255), nullable=True),
    sa.Column('fan_16_status', sa.String(length=255), nullable=True),
    sa.Column('fan_17_status', sa.String(length=255), nullable=True),
    sa.Column('fan_18_status', sa.String(length=255), nullable=True),
    sa.Column('fan_19_status', sa.String(length=255), nullable=True),
    sa.Column('fan_20_status', sa.String(length=255), nullable=True),
    sa.Column('fan_21_status', sa.String(length=255), nullable=True),
    sa.Column('fan_22_status', sa.String(length=255), nullable=True),
    sa.Column('fan_23_status', sa.String(length=255), nullable=True),
    sa.Column('dc_section_fan_status', sa.String(length=255), nullable=True),
    sa.Column('line_1_over_voltage', sa.String(length=255), nullable=True),
    sa.Column('line_2_over_voltage', sa.String(length=255), nullable=True),
    sa.Column('line_3_over_voltage', sa.String(length=255), nullable=True),
    sa.Column('line_1_under_voltage', sa.String(length=255), nullable=True),
    sa.Column('line_2_under_voltage', sa.String(length=255), nullable=True),
    sa.Column('line_3_under_voltage', sa.String(length=255), nullable=True),
    sa.Column('system_over_temperature', sa.String(length=255), nullable=True),
    sa.Column('system_tilted', sa.String(length=255), nullable=True),
    sa.Column('temperature_sensor_disconnected', sa.String(length=255), nullable=True),
    sa.Column('mains_high', sa.String(length=255), nullable=True),
    sa.Column('mains_low', sa.String(length=255), nullable=True),
    sa.Column('sd_card_not_present', sa.String(length=255), nullable=True),
    sa.Column('temperature_sensor_1_fail', sa.String(length=255), nullable=True),
    sa.Column('temperature_sensor_2_fail', sa.String(length=255), nullable=True),
    sa.Column('dcem_sn_duplicate', sa.String(length=255), nullable=True),
    sa.Column('grid_over_voltage', sa.String(length=255), nullable=True),
    sa.Column('grid_under_voltage', sa.String(length=255), nullable=True),
    sa.Column('ocpp_state', sa.String(length=255), nullable=True),
    sa.Column('pilot_controller_state', sa.String(length=255), nullable=True),
    sa.Column('ccu_main_state', sa.String(length=255), nullable=True),
    sa.Column('cp_voltage', sa.Float(), nullable=True),
    sa.Column('set_voltage', sa.Float(), nullable=True),
    sa.Column('set_current', sa.Float(), nullable=True),
    sa.Column('output_voltage', sa.Float(), nullable=True),
    sa.Column('output_current', sa.Float(), nullable=True),
    sa.Column('available_max_current', sa.Float(), nullable=True),
    sa.Column('available_max_power', sa.Float(), nullable=True),
    sa.Column('dc_over_voltage', sa.String(length=255), nullable=True),
    sa.Column('e_lock_failed', sa.String(length=255), nullable=True),
    sa.Column('auxillary_power_fail', sa.String(length=255), nullable=True),
    sa.Column('voltage_calibration_error', sa.String(length=255), nullable=True),
    sa.Column('power_section_failed', sa.String(length=255), nullable=True),
    sa.Column('ems_output_voltage', sa.Float(), nullable=True),
    sa.Column('ems_output_current', sa.Float(), nullable=True),
    sa.Column('ems_output_power', sa.Float(), nullable=True),
    sa.Column('ac_over_voltage', sa.String(length=255), nullable=True),
    sa.Column('ac_under_voltage', sa.String(length=255), nullable=True),
    sa.Column('charging_time', sa.Float(), nullable=True),
    sa.Column('ocpp_tx_send_status', sa.String(length=255), nullable=True),
    sa.Column('ev_mac_id_info', sa.String(length=255), nullable=True),
    sa.Column('slac_attenuation', sa.Float(), nullable=True),
    sa.Column('discharge_abnormal', sa.String(length=255), nullable=True),
    sa.Column('dc_side_is_off', sa.String(length=255), nullable=True),
    sa.Column('mdl_protect', sa.String(length=255), nullable=True),
    sa.Column('over_temperature', sa.String(length=255), nullable=True),
    sa.Column('output_over_voltage', sa.String(length=255), nullable=True),
    sa.Column('walk_in_enabled', sa.String(length=255), nullable=True),
    sa.Column('mdl_id_repetition', sa.String(length=255), nullable=True),
    sa.Column('load_sharing', sa.String(length=255), nullable=True),
    sa.Column('input_phase_loss', sa.String(length=255), nullable=True),
    sa.Column('input_unbalance', sa.String(length=255), nullable=True),
    sa.Column('input_under_voltage', sa.String(length=255), nullable=True),
    sa.Column('input_over_voltage', sa.String(length=255), nullable=True),
    sa.Column('fuse_burn_out', sa.String(length=255), nullable=True),
    sa.Column('bus_unbalanced_voltage', sa.String(length=255), nullable=True),
    sa.Column('bus_over_voltage', sa.String(length=255), nullable=True),
    sa.Column('bus_voltage_abnormal', sa.String(length=255), nullable=True),
    sa.Column('bus_under_voltage', sa.String(length=255), nullable=True),
    sa.Column('fan_at_full_speed', sa.String(length=255), nullable=True),
    sa.Column('output_derating_temp', sa.String(length=255), nullable=True),
    sa.Column('output_derating_ac', sa.String(length=255), nullable=True),
    sa.Column('back_up_battery_voltage', sa.Float(), nullable=True),
    sa.Column('run_since_power_on', sa.Float(), nullable=True),
    sa.Column('last_charger_reboot_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['telemetry_source_frame.id'], name=op.f('fk_silver_charger_telemetry_frame_id_telemetry_source_frame'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_silver_charger_telemetry')),
    sa.UniqueConstraint('charger_id', 'event_time', 'frame_sequence', name='uq_silver_charger_telemetry')
    )
    op.create_index(op.f('ix_silver_charger_telemetry_charger_id'), 'silver_charger_telemetry', ['charger_id'], unique=False)
    op.create_index(op.f('ix_silver_charger_telemetry_event_time'), 'silver_charger_telemetry', ['event_time'], unique=False)
    op.create_index(op.f('ix_silver_charger_telemetry_frame_id'), 'silver_charger_telemetry', ['frame_id'], unique=False)
    op.create_index('ix_silver_charger_telemetry_lookup', 'silver_charger_telemetry', ['charger_id', 'event_time', 'frame_sequence'], unique=False)
    op.create_table('silver_communication_observation',
    sa.Column('charger_id', sa.String(length=128), nullable=False),
    sa.Column('event_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('frame_sequence', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Uuid(), nullable=False),
    sa.Column('ccu_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('led_strip_card_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('dcsi_card_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('ac_sense_card_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('led_board_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('rfid_reader_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('modem_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('modem_sim_present', sa.String(length=255), nullable=True),
    sa.Column('display_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('cms_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('fan_card_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('i_o_card_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('input_acem_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('led_card2_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('rsrp', sa.Float(), nullable=True),
    sa.Column('rsrq', sa.Float(), nullable=True),
    sa.Column('gmd_comm_fail_alarm', sa.String(length=255), nullable=True),
    sa.Column('ring_communication_break', sa.String(length=255), nullable=True),
    sa.Column('sim_not_inserted_alarm', sa.String(length=255), nullable=True),
    sa.Column('insulation_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('plc_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('energy_meter_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('ac_energy_meter_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('inner_comm_interrupt', sa.String(length=255), nullable=True),
    sa.Column('can_communication_interrupt', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['telemetry_source_frame.id'], name=op.f('fk_silver_communication_observation_frame_id_telemetry_source_frame'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_silver_communication_observation')),
    sa.UniqueConstraint('charger_id', 'event_time', 'frame_sequence', name='uq_silver_communication_observation')
    )
    op.create_index(op.f('ix_silver_communication_observation_charger_id'), 'silver_communication_observation', ['charger_id'], unique=False)
    op.create_index(op.f('ix_silver_communication_observation_event_time'), 'silver_communication_observation', ['event_time'], unique=False)
    op.create_index(op.f('ix_silver_communication_observation_frame_id'), 'silver_communication_observation', ['frame_id'], unique=False)
    op.create_index('ix_silver_communication_observation_lookup', 'silver_communication_observation', ['charger_id', 'event_time', 'frame_sequence'], unique=False)
    op.create_table('silver_configuration_snapshot',
    sa.Column('charger_id', sa.String(length=128), nullable=False),
    sa.Column('event_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('frame_sequence', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Uuid(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('modem_signal_intensity', sa.Float(), nullable=True),
    sa.Column('charge_selected_mode', sa.String(length=255), nullable=True),
    sa.Column('charging_start_method', sa.String(length=255), nullable=True),
    sa.Column('charging_mode', sa.String(length=255), nullable=True),
    sa.Column('ev_max_voltage_limit', sa.Float(), nullable=True),
    sa.Column('ev_max_current_limit', sa.Float(), nullable=True),
    sa.Column('power_limit', sa.String(length=255), nullable=True),
    sa.Column('ring_current_operating_mode', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['telemetry_source_frame.id'], name=op.f('fk_silver_configuration_snapshot_frame_id_telemetry_source_frame'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_silver_configuration_snapshot')),
    sa.UniqueConstraint('charger_id', 'event_time', 'frame_sequence', name='uq_silver_configuration_snapshot')
    )
    op.create_index(op.f('ix_silver_configuration_snapshot_charger_id'), 'silver_configuration_snapshot', ['charger_id'], unique=False)
    op.create_index(op.f('ix_silver_configuration_snapshot_config_hash'), 'silver_configuration_snapshot', ['config_hash'], unique=False)
    op.create_index(op.f('ix_silver_configuration_snapshot_event_time'), 'silver_configuration_snapshot', ['event_time'], unique=False)
    op.create_index(op.f('ix_silver_configuration_snapshot_frame_id'), 'silver_configuration_snapshot', ['frame_id'], unique=False)
    op.create_index('ix_silver_configuration_snapshot_lookup', 'silver_configuration_snapshot', ['charger_id', 'event_time', 'frame_sequence'], unique=False)
    op.create_table('silver_connector_telemetry',
    sa.Column('charger_id', sa.String(length=128), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('event_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('frame_sequence', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Uuid(), nullable=False),
    sa.Column('gun_temp_dc_positive_raw', sa.Float(), nullable=True),
    sa.Column('gun_temp_dc_positive_masked', sa.Boolean(), nullable=False),
    sa.Column('gun_temp_dc_negative_raw', sa.Float(), nullable=True),
    sa.Column('gun_temp_dc_negative_masked', sa.Boolean(), nullable=False),
    sa.Column('connector_type', sa.String(length=255), nullable=True),
    sa.Column('connector_status', sa.String(length=255), nullable=True),
    sa.Column('plug_status', sa.String(length=255), nullable=True),
    sa.Column('ccs_main_state', sa.String(length=255), nullable=True),
    sa.Column('ccs_sub_state', sa.String(length=255), nullable=True),
    sa.Column('gun_temp_dc_positive', sa.Float(), nullable=True),
    sa.Column('gun_temp_dc_negative', sa.Float(), nullable=True),
    sa.Column('gun_insertion_cycle_count', sa.Float(), nullable=True),
    sa.Column('gun_voltage', sa.Float(), nullable=True),
    sa.Column('gun_over_temp_warning', sa.String(length=255), nullable=True),
    sa.Column('gun_over_temp_cutoff', sa.String(length=255), nullable=True),
    sa.Column('gun_over_temp_dc_positive_warning', sa.String(length=255), nullable=True),
    sa.Column('gun_over_temp_dc_negative_warning', sa.String(length=255), nullable=True),
    sa.Column('gun_ov_temp_derating_set', sa.String(length=255), nullable=True),
    sa.Column('gun_locked_by_cms', sa.String(length=255), nullable=True),
    sa.Column('gun_temperature_derating_status', sa.String(length=255), nullable=True),
    sa.Column('gun_dc_positive_ultra_temp', sa.String(length=255), nullable=True),
    sa.Column('gun_dc_negative_ultra_temp', sa.String(length=255), nullable=True),
    sa.Column('gun_dc_positive_temp_sensor_disconnect', sa.String(length=255), nullable=True),
    sa.Column('gun_dc_negative_temp_sensor_disconnect', sa.String(length=255), nullable=True),
    sa.Column('gun_temperature_sensor_disconnect', sa.String(length=255), nullable=True),
    sa.Column('gun_dc_positive_temp_sensor_loose', sa.String(length=255), nullable=True),
    sa.Column('gun_dc_negative_temp_sensor_loose', sa.String(length=255), nullable=True),
    sa.Column('gun_not_placed_back_alarm', sa.String(length=255), nullable=True),
    sa.Column('ccs_secc_state', sa.String(length=255), nullable=True),
    sa.Column('ccs_secc_error_code', sa.String(length=255), nullable=True),
    sa.Column('ccs_ev_error_code', sa.String(length=255), nullable=True),
    sa.Column('gun_output_voltage', sa.Float(), nullable=True),
    sa.Column('gun_ccs_main_state_at_session_stop', sa.String(length=255), nullable=True),
    sa.Column('gun_ccs_sub_state_at_session_stop', sa.String(length=255), nullable=True),
    sa.Column('gun_insert_counter_charger_socket', sa.Float(), nullable=True),
    sa.Column('gun_over_temperature_counter', sa.Float(), nullable=True),
    sa.Column('gun_placed_in_charger_holder', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['telemetry_source_frame.id'], name=op.f('fk_silver_connector_telemetry_frame_id_telemetry_source_frame'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_silver_connector_telemetry')),
    sa.UniqueConstraint('charger_id', 'connector_id', 'event_time', 'frame_sequence', name='uq_silver_connector_telemetry')
    )
    op.create_index(op.f('ix_silver_connector_telemetry_charger_id'), 'silver_connector_telemetry', ['charger_id'], unique=False)
    op.create_index(op.f('ix_silver_connector_telemetry_connector_id'), 'silver_connector_telemetry', ['connector_id'], unique=False)
    op.create_index(op.f('ix_silver_connector_telemetry_event_time'), 'silver_connector_telemetry', ['event_time'], unique=False)
    op.create_index(op.f('ix_silver_connector_telemetry_frame_id'), 'silver_connector_telemetry', ['frame_id'], unique=False)
    op.create_index('ix_silver_connector_telemetry_lookup', 'silver_connector_telemetry', ['charger_id', 'connector_id', 'event_time', 'frame_sequence'], unique=False)
    op.create_table('silver_contactor_observation',
    sa.Column('charger_id', sa.String(length=128), nullable=False),
    sa.Column('event_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('frame_sequence', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Uuid(), nullable=False),
    sa.Column('ac_contactor_status', sa.String(length=255), nullable=True),
    sa.Column('input_contactor_fail', sa.String(length=255), nullable=True),
    sa.Column('gun_dc_contactor_fail', sa.String(length=255), nullable=True),
    sa.Column('ac_contactor_switching_cycle', sa.String(length=255), nullable=True),
    sa.Column('ac_contactor_feedback_status', sa.String(length=255), nullable=True),
    sa.Column('dc_contactor_switching_cycle', sa.Float(), nullable=True),
    sa.Column('ac1_contactor_status', sa.String(length=255), nullable=True),
    sa.Column('ac2_contactor_status', sa.String(length=255), nullable=True),
    sa.Column('ac3_contactor_status', sa.String(length=255), nullable=True),
    sa.Column('ac4_contactor_status', sa.String(length=255), nullable=True),
    sa.Column('ac5_contactor_status', sa.String(length=255), nullable=True),
    sa.Column('ac6_contactor_status', sa.String(length=255), nullable=True),
    sa.Column('ac1_contactor_cycle_count', sa.Float(), nullable=True),
    sa.Column('ac2_contactor_cycle_count', sa.Float(), nullable=True),
    sa.Column('ac3_contactor_cycle_count', sa.Float(), nullable=True),
    sa.Column('ac4_contactor_cycle_count', sa.Float(), nullable=True),
    sa.Column('ac5_contactor_cycle_count', sa.Float(), nullable=True),
    sa.Column('ac6_contactor_cycle_count', sa.Float(), nullable=True),
    sa.Column('ac1_contactor_fail_alarm', sa.String(length=255), nullable=True),
    sa.Column('ac2_contactor_fail_alarm', sa.String(length=255), nullable=True),
    sa.Column('ac3_contactor_fail_alarm', sa.String(length=255), nullable=True),
    sa.Column('ac4_contactor_fail_alarm', sa.String(length=255), nullable=True),
    sa.Column('ac5_contactor_fail_alarm', sa.String(length=255), nullable=True),
    sa.Column('ac6_contactor_fail_alarm', sa.String(length=255), nullable=True),
    sa.Column('ac1_contactor_welded_alarm', sa.String(length=255), nullable=True),
    sa.Column('ac2_contactor_welded_alarm', sa.String(length=255), nullable=True),
    sa.Column('ac3_contactor_welded_alarm', sa.String(length=255), nullable=True),
    sa.Column('ac4_contactor_welded_alarm', sa.String(length=255), nullable=True),
    sa.Column('ac5_contactor_welded_alarm', sa.String(length=255), nullable=True),
    sa.Column('ac6_contactor_welded_alarm', sa.String(length=255), nullable=True),
    sa.Column('dc_merger_contactor_c0_cycle_count', sa.Float(), nullable=True),
    sa.Column('dc_merger_contactor_c1_cycle_count', sa.Float(), nullable=True),
    sa.Column('dc_merger_contactor_c2_cycle_count', sa.Float(), nullable=True),
    sa.Column('dc_merger_contactor_c3_cycle_count', sa.Float(), nullable=True),
    sa.Column('dc_merger_contactor_c4_cycle_count', sa.Float(), nullable=True),
    sa.Column('external_contactor_cycle_count_ring', sa.Float(), nullable=True),
    sa.Column('merger_contactor_c0_fail_alarm', sa.String(length=255), nullable=True),
    sa.Column('merger_contactor_c1_fail_alarm', sa.String(length=255), nullable=True),
    sa.Column('merger_contactor_c2_fail_alarm', sa.String(length=255), nullable=True),
    sa.Column('merger_contactor_c3_fail_alarm', sa.String(length=255), nullable=True),
    sa.Column('merger_contactor_c4_fail_alarm', sa.String(length=255), nullable=True),
    sa.Column('external_contactor_fail_alarm_ring', sa.String(length=255), nullable=True),
    sa.Column('merger_contactor_c0_welded_alarm', sa.String(length=255), nullable=True),
    sa.Column('merger_contactor_c1_welded_alarm', sa.String(length=255), nullable=True),
    sa.Column('merger_contactor_c2_welded_alarm', sa.String(length=255), nullable=True),
    sa.Column('merger_contactor_c3_welded_alarm', sa.String(length=255), nullable=True),
    sa.Column('merger_contactor_c4_welded_alarm', sa.String(length=255), nullable=True),
    sa.Column('c0_merger_contactor_status', sa.String(length=255), nullable=True),
    sa.Column('c1_merger_contactor_status', sa.String(length=255), nullable=True),
    sa.Column('c2_merger_contactor_status', sa.String(length=255), nullable=True),
    sa.Column('c3_merger_contactor_status', sa.String(length=255), nullable=True),
    sa.Column('c4_merger_contactor_status', sa.String(length=255), nullable=True),
    sa.Column('external_contactor_status', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['telemetry_source_frame.id'], name=op.f('fk_silver_contactor_observation_frame_id_telemetry_source_frame'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_silver_contactor_observation')),
    sa.UniqueConstraint('charger_id', 'event_time', 'frame_sequence', name='uq_silver_contactor_observation')
    )
    op.create_index(op.f('ix_silver_contactor_observation_charger_id'), 'silver_contactor_observation', ['charger_id'], unique=False)
    op.create_index(op.f('ix_silver_contactor_observation_event_time'), 'silver_contactor_observation', ['event_time'], unique=False)
    op.create_index(op.f('ix_silver_contactor_observation_frame_id'), 'silver_contactor_observation', ['frame_id'], unique=False)
    op.create_index('ix_silver_contactor_observation_lookup', 'silver_contactor_observation', ['charger_id', 'event_time', 'frame_sequence'], unique=False)
    op.create_table('silver_lifecycle_counter_observation',
    sa.Column('charger_id', sa.String(length=128), nullable=False),
    sa.Column('event_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('frame_sequence', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Uuid(), nullable=False),
    sa.Column('ems_cumulative_energy', sa.Float(), nullable=True),
    sa.Column('charging_cycle_count', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['telemetry_source_frame.id'], name=op.f('fk_silver_lifecycle_counter_observation_frame_id_telemetry_source_frame'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_silver_lifecycle_counter_observation')),
    sa.UniqueConstraint('charger_id', 'event_time', 'frame_sequence', name='uq_silver_lifecycle_counter_observation')
    )
    op.create_index(op.f('ix_silver_lifecycle_counter_observation_charger_id'), 'silver_lifecycle_counter_observation', ['charger_id'], unique=False)
    op.create_index(op.f('ix_silver_lifecycle_counter_observation_event_time'), 'silver_lifecycle_counter_observation', ['event_time'], unique=False)
    op.create_index(op.f('ix_silver_lifecycle_counter_observation_frame_id'), 'silver_lifecycle_counter_observation', ['frame_id'], unique=False)
    op.create_index('ix_silver_lifecycle_counter_observation_lookup', 'silver_lifecycle_counter_observation', ['charger_id', 'event_time', 'frame_sequence'], unique=False)
    op.create_table('silver_normalization_run',
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('frames_input', sa.Integer(), nullable=False),
    sa.Column('frames_normalized', sa.Integer(), nullable=False),
    sa.Column('frames_with_warnings', sa.Integer(), nullable=False),
    sa.Column('frames_failed', sa.Integer(), nullable=False),
    sa.Column('records_created_by_table', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sentinels_masked_count', sa.Integer(), nullable=False),
    sa.Column('conflicts_detected_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['telemetry_file.id'], name=op.f('fk_silver_normalization_run_file_id_telemetry_file'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_silver_normalization_run'))
    )
    op.create_index(op.f('ix_silver_normalization_run_file_id'), 'silver_normalization_run', ['file_id'], unique=False)
    op.create_table('silver_observation_provenance',
    sa.Column('silver_table_name', sa.String(length=64), nullable=False),
    sa.Column('silver_record_id', sa.Uuid(), nullable=False),
    sa.Column('frame_id', sa.Uuid(), nullable=False),
    sa.Column('bronze_row_id', sa.Uuid(), nullable=True),
    sa.Column('source_file_id', sa.Uuid(), nullable=False),
    sa.Column('source_position', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=128), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('transformation_applied', sa.String(length=128), nullable=True),
    sa.Column('masked_sentinel', sa.Boolean(), nullable=False),
    sa.Column('created_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['telemetry_source_frame.id'], name=op.f('fk_silver_observation_provenance_frame_id_telemetry_source_frame'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['telemetry_file.id'], name=op.f('fk_silver_observation_provenance_source_file_id_telemetry_file'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_silver_observation_provenance'))
    )
    op.create_index(op.f('ix_silver_observation_provenance_bronze_row_id'), 'silver_observation_provenance', ['bronze_row_id'], unique=False)
    op.create_index(op.f('ix_silver_observation_provenance_frame_id'), 'silver_observation_provenance', ['frame_id'], unique=False)
    op.create_index(op.f('ix_silver_observation_provenance_silver_record_id'), 'silver_observation_provenance', ['silver_record_id'], unique=False)
    op.create_index(op.f('ix_silver_observation_provenance_silver_table_name'), 'silver_observation_provenance', ['silver_table_name'], unique=False)
    op.create_index(op.f('ix_silver_observation_provenance_source_file_id'), 'silver_observation_provenance', ['source_file_id'], unique=False)
    op.create_index('ix_silver_provenance_frame', 'silver_observation_provenance', ['frame_id'], unique=False)
    op.create_index('ix_silver_provenance_record', 'silver_observation_provenance', ['silver_table_name', 'silver_record_id'], unique=False)
    op.create_table('silver_rectifier_telemetry',
    sa.Column('charger_id', sa.String(length=128), nullable=False),
    sa.Column('rectifier_id', sa.Integer(), nullable=False),
    sa.Column('event_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('frame_sequence', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Uuid(), nullable=False),
    sa.Column('rect_max_temperature_raw', sa.Float(), nullable=True),
    sa.Column('rect_max_temperature_masked', sa.Boolean(), nullable=False),
    sa.Column('rectifier_internal_temp_raw', sa.Float(), nullable=True),
    sa.Column('rectifier_internal_temp_masked', sa.Boolean(), nullable=False),
    sa.Column('rect_max_temperature', sa.Float(), nullable=True),
    sa.Column('all_rectifier_fail', sa.String(length=255), nullable=True),
    sa.Column('all_rectifier_communication_fail', sa.String(length=255), nullable=True),
    sa.Column('any_rect_fail', sa.String(length=255), nullable=True),
    sa.Column('any_rect_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('no_of_active_rectifiers', sa.Float(), nullable=True),
    sa.Column('group_rect_fail', sa.String(length=255), nullable=True),
    sa.Column('group_rect_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('gun_rect_fail', sa.String(length=255), nullable=True),
    sa.Column('gun_rect_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('rectifier_dc_status', sa.String(length=255), nullable=True),
    sa.Column('rectifier_internal_temp', sa.Float(), nullable=True),
    sa.Column('rectifier_output_voltage', sa.Float(), nullable=True),
    sa.Column('rectifier_output_current', sa.Float(), nullable=True),
    sa.Column('rectifier_available_max_voltage', sa.Float(), nullable=True),
    sa.Column('rectifier_available_max_current', sa.Float(), nullable=True),
    sa.Column('rectifier_available_max_power', sa.Float(), nullable=True),
    sa.Column('rectifier_output_short', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['telemetry_source_frame.id'], name=op.f('fk_silver_rectifier_telemetry_frame_id_telemetry_source_frame'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_silver_rectifier_telemetry')),
    sa.UniqueConstraint('charger_id', 'rectifier_id', 'event_time', 'frame_sequence', name='uq_silver_rectifier_telemetry')
    )
    op.create_index(op.f('ix_silver_rectifier_telemetry_charger_id'), 'silver_rectifier_telemetry', ['charger_id'], unique=False)
    op.create_index(op.f('ix_silver_rectifier_telemetry_event_time'), 'silver_rectifier_telemetry', ['event_time'], unique=False)
    op.create_index(op.f('ix_silver_rectifier_telemetry_frame_id'), 'silver_rectifier_telemetry', ['frame_id'], unique=False)
    op.create_index('ix_silver_rectifier_telemetry_lookup', 'silver_rectifier_telemetry', ['charger_id', 'rectifier_id', 'event_time', 'frame_sequence'], unique=False)
    op.create_index(op.f('ix_silver_rectifier_telemetry_rectifier_id'), 'silver_rectifier_telemetry', ['rectifier_id'], unique=False)
    op.create_table('silver_session_observation',
    sa.Column('charger_id', sa.String(length=128), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('event_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('frame_sequence', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Uuid(), nullable=False),
    sa.Column('stop_reason', sa.String(length=255), nullable=True),
    sa.Column('last_charge_session_stop_reason', sa.String(length=255), nullable=True),
    sa.Column('session_type', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.Float(), nullable=True),
    sa.Column('session_output_voltage', sa.Float(), nullable=True),
    sa.Column('session_output_current', sa.Float(), nullable=True),
    sa.Column('session_demand_voltage', sa.Float(), nullable=True),
    sa.Column('session_demand_current', sa.Float(), nullable=True),
    sa.Column('session_start_energy', sa.Float(), nullable=True),
    sa.Column('session_consumed_energy', sa.Float(), nullable=True),
    sa.Column('start_soc', sa.Float(), nullable=True),
    sa.Column('stop_soc', sa.Float(), nullable=True),
    sa.Column('begin_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('last_charge_session_stop_reason_secondary', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['telemetry_source_frame.id'], name=op.f('fk_silver_session_observation_frame_id_telemetry_source_frame'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_silver_session_observation')),
    sa.UniqueConstraint('charger_id', 'connector_id', 'event_time', 'frame_sequence', name='uq_silver_session_observation')
    )
    op.create_index(op.f('ix_silver_session_observation_charger_id'), 'silver_session_observation', ['charger_id'], unique=False)
    op.create_index(op.f('ix_silver_session_observation_connector_id'), 'silver_session_observation', ['connector_id'], unique=False)
    op.create_index(op.f('ix_silver_session_observation_event_time'), 'silver_session_observation', ['event_time'], unique=False)
    op.create_index(op.f('ix_silver_session_observation_frame_id'), 'silver_session_observation', ['frame_id'], unique=False)
    op.create_index('ix_silver_session_observation_lookup', 'silver_session_observation', ['charger_id', 'connector_id', 'event_time', 'frame_sequence'], unique=False)
    op.create_table('silver_site_metadata',
    sa.Column('charger_id', sa.String(length=128), nullable=False),
    sa.Column('event_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('frame_sequence', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Uuid(), nullable=False),
    sa.Column('charging_station', sa.String(length=255), nullable=True),
    sa.Column('site_address', sa.String(length=255), nullable=True),
    sa.Column('site_city', sa.String(length=128), nullable=True),
    sa.Column('site_state', sa.String(length=128), nullable=True),
    sa.Column('site_pin', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['telemetry_source_frame.id'], name=op.f('fk_silver_site_metadata_frame_id_telemetry_source_frame'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_silver_site_metadata')),
    sa.UniqueConstraint('charger_id', 'event_time', 'frame_sequence', name='uq_silver_site_metadata')
    )
    op.create_index(op.f('ix_silver_site_metadata_charger_id'), 'silver_site_metadata', ['charger_id'], unique=False)
    op.create_index(op.f('ix_silver_site_metadata_event_time'), 'silver_site_metadata', ['event_time'], unique=False)
    op.create_index(op.f('ix_silver_site_metadata_frame_id'), 'silver_site_metadata', ['frame_id'], unique=False)
    op.create_table('silver_smr_telemetry',
    sa.Column('charger_id', sa.String(length=128), nullable=False),
    sa.Column('smr_id', sa.Integer(), nullable=False),
    sa.Column('event_time', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('frame_sequence', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Uuid(), nullable=False),
    sa.Column('smr_dc_dc_temperature_raw', sa.Float(), nullable=True),
    sa.Column('smr_dc_dc_temperature_masked', sa.Boolean(), nullable=False),
    sa.Column('smr_pfc_temperature_raw', sa.Float(), nullable=True),
    sa.Column('smr_pfc_temperature_masked', sa.Boolean(), nullable=False),
    sa.Column('smr_rectifierinternal_temp_raw', sa.Float(), nullable=True),
    sa.Column('smr_rectifierinternal_temp_masked', sa.Boolean(), nullable=False),
    sa.Column('smrdcdc_temperature_raw', sa.Float(), nullable=True),
    sa.Column('smrdcdc_temperature_masked', sa.Boolean(), nullable=False),
    sa.Column('smrpfc_temperature_raw', sa.Float(), nullable=True),
    sa.Column('smrpfc_temperature_masked', sa.Boolean(), nullable=False),
    sa.Column('smr_set_voltage', sa.Float(), nullable=True),
    sa.Column('smr_set_current', sa.Float(), nullable=True),
    sa.Column('smr_available_current', sa.Float(), nullable=True),
    sa.Column('smr_max_power', sa.Float(), nullable=True),
    sa.Column('smr_dc_dc_temperature', sa.Float(), nullable=True),
    sa.Column('smr_pfc_temperature', sa.Float(), nullable=True),
    sa.Column('smr_hardware_version', sa.String(length=255), nullable=True),
    sa.Column('smr_software_version', sa.String(length=255), nullable=True),
    sa.Column('pfc_side_abnormal', sa.String(length=255), nullable=True),
    sa.Column('pfc_side_is_off', sa.String(length=255), nullable=True),
    sa.Column('pfc_dcdc_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('pfc_eeprom_faults', sa.String(length=255), nullable=True),
    sa.Column('smr_mapped_gun', sa.Float(), nullable=True),
    sa.Column('smr_group_id', sa.String(length=255), nullable=True),
    sa.Column('smr_output_voltage', sa.Float(), nullable=True),
    sa.Column('smr_output_current', sa.Float(), nullable=True),
    sa.Column('smr_output_power', sa.Float(), nullable=True),
    sa.Column('smr_available_max_current', sa.Float(), nullable=True),
    sa.Column('smr_available_max_power', sa.Float(), nullable=True),
    sa.Column('smr_rectifier_d_cstatus', sa.String(length=255), nullable=True),
    sa.Column('smr_rectifierinternal_temp', sa.Float(), nullable=True),
    sa.Column('smrdcdc_temperature', sa.Float(), nullable=True),
    sa.Column('smrpfc_temperature', sa.Float(), nullable=True),
    sa.Column('smr_available_max_voltage', sa.Float(), nullable=True),
    sa.Column('smr_rated_maximum_current', sa.Float(), nullable=True),
    sa.Column('smr_rated_maximum_power', sa.Float(), nullable=True),
    sa.Column('smr_module_hardware_version', sa.Float(), nullable=True),
    sa.Column('smr_module_software_version', sa.String(length=255), nullable=True),
    sa.Column('smrpfc_ver', sa.Float(), nullable=True),
    sa.Column('smr_line1_voltage', sa.Float(), nullable=True),
    sa.Column('smr_line2_voltage', sa.Float(), nullable=True),
    sa.Column('smr_line3_voltage', sa.Float(), nullable=True),
    sa.Column('smr_rated_minimum_voltage', sa.Float(), nullable=True),
    sa.Column('smr_rated_maximum_voltage', sa.Float(), nullable=True),
    sa.Column('smr_fan_speed', sa.Float(), nullable=True),
    sa.Column('smr_output_short', sa.String(length=255), nullable=True),
    sa.Column('smr_inner_comm_interrupt', sa.String(length=255), nullable=True),
    sa.Column('smr_pfc_side_abnormal', sa.String(length=255), nullable=True),
    sa.Column('smr_discharge_abnormal', sa.String(length=255), nullable=True),
    sa.Column('smr_dc_side_is_off', sa.String(length=255), nullable=True),
    sa.Column('smr_mdl_fault', sa.String(length=255), nullable=True),
    sa.Column('smr_mdl_protect', sa.String(length=255), nullable=True),
    sa.Column('smr_fan_fault', sa.String(length=255), nullable=True),
    sa.Column('smr_over_temperature', sa.String(length=255), nullable=True),
    sa.Column('smr_output_over_voltage', sa.String(length=255), nullable=True),
    sa.Column('smr_walk_in_enable', sa.String(length=255), nullable=True),
    sa.Column('smr_can_communication_interrupt', sa.String(length=255), nullable=True),
    sa.Column('smr_power_limit', sa.String(length=255), nullable=True),
    sa.Column('smr_dl_id_repetition', sa.String(length=255), nullable=True),
    sa.Column('smr_load_sharing', sa.String(length=255), nullable=True),
    sa.Column('smr_input_phase_loss', sa.String(length=255), nullable=True),
    sa.Column('smr_input_unbalance', sa.String(length=255), nullable=True),
    sa.Column('smr_input_under_voltage', sa.String(length=255), nullable=True),
    sa.Column('smr_input_over_voltage', sa.String(length=255), nullable=True),
    sa.Column('smr_pfc_side_is_off', sa.String(length=255), nullable=True),
    sa.Column('smr_fuse_burn_out', sa.String(length=255), nullable=True),
    sa.Column('smr_pfc_dcdc_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('smr_bus_unbalanced_voltage', sa.String(length=255), nullable=True),
    sa.Column('smr_bus_over_voltage', sa.String(length=255), nullable=True),
    sa.Column('smr_bus_voltage_abnormal', sa.String(length=255), nullable=True),
    sa.Column('smr_bus_under_voltage', sa.String(length=255), nullable=True),
    sa.Column('smr_fan_at_full_speed', sa.String(length=255), nullable=True),
    sa.Column('smr_output_derating_temp', sa.String(length=255), nullable=True),
    sa.Column('smr_output_derating_ac', sa.String(length=255), nullable=True),
    sa.Column('smr_dcdc_eeprom_faults', sa.String(length=255), nullable=True),
    sa.Column('smr_pfc_eeprom_faults', sa.String(length=255), nullable=True),
    sa.Column('smr_module_fail', sa.String(length=255), nullable=True),
    sa.Column('smr_module_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('in_pfc_1', sa.String(length=255), nullable=True),
    sa.Column('in_pfc_2', sa.String(length=255), nullable=True),
    sa.Column('in_pfc_3', sa.String(length=255), nullable=True),
    sa.Column('in_pfc_4', sa.String(length=255), nullable=True),
    sa.Column('in_pfc_5', sa.String(length=255), nullable=True),
    sa.Column('in_pfc_6', sa.String(length=255), nullable=True),
    sa.Column('in_pfc_7', sa.String(length=255), nullable=True),
    sa.Column('in_pfc_8', sa.String(length=255), nullable=True),
    sa.Column('in_pfc_9', sa.String(length=255), nullable=True),
    sa.Column('in_pfc_10', sa.String(length=255), nullable=True),
    sa.Column('in_pfc_11', sa.String(length=255), nullable=True),
    sa.Column('in_pfc_12', sa.String(length=255), nullable=True),
    sa.Column('out_pfc_1', sa.String(length=255), nullable=True),
    sa.Column('out_pfc_2', sa.String(length=255), nullable=True),
    sa.Column('out_pfc_3', sa.String(length=255), nullable=True),
    sa.Column('out_pfc_4', sa.String(length=255), nullable=True),
    sa.Column('out_pfc_5', sa.String(length=255), nullable=True),
    sa.Column('out_pfc_6', sa.String(length=255), nullable=True),
    sa.Column('out_pfc_7', sa.String(length=255), nullable=True),
    sa.Column('out_pfc_8', sa.String(length=255), nullable=True),
    sa.Column('out_pfc_9', sa.String(length=255), nullable=True),
    sa.Column('out_pfc_10', sa.String(length=255), nullable=True),
    sa.Column('out_pfc_11', sa.String(length=255), nullable=True),
    sa.Column('out_pfc_12', sa.String(length=255), nullable=True),
    sa.Column('floating_smr1_fail', sa.String(length=255), nullable=True),
    sa.Column('floating_smr1_group_fail', sa.String(length=255), nullable=True),
    sa.Column('floating_smr1_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('floating_smr1_group_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('floating_smr2_fail', sa.String(length=255), nullable=True),
    sa.Column('floating_smr2_group_fail', sa.String(length=255), nullable=True),
    sa.Column('floating_smr2_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('floating_smr2_group_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('floating_smr3_fail', sa.String(length=255), nullable=True),
    sa.Column('floating_smr3_group_fail', sa.String(length=255), nullable=True),
    sa.Column('floating_smr3_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('floating_smr3_group_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('floating_smr4_fail', sa.String(length=255), nullable=True),
    sa.Column('floating_smr4_group_fail', sa.String(length=255), nullable=True),
    sa.Column('floating_smr4_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('floating_smr4_group_comm_fail', sa.String(length=255), nullable=True),
    sa.Column('smr_fail_count', sa.Float(), nullable=True),
    sa.Column('smr_comm_fail_count', sa.Float(), nullable=True),
    sa.Column('guna_smr_fail_count', sa.Float(), nullable=True),
    sa.Column('guna_smr_comm_fail_count', sa.Float(), nullable=True),
    sa.Column('gunb_smr_fail_count', sa.Float(), nullable=True),
    sa.Column('gunb_smr_comm_fail_count', sa.Float(), nullable=True),
    sa.Column('fr1_smr_fail_count', sa.Float(), nullable=True),
    sa.Column('fr1_smr_comm_fail_count', sa.Float(), nullable=True),
    sa.Column('fr2_smr_fail_count', sa.Float(), nullable=True),
    sa.Column('fr2_smr_comm_fail_count', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['telemetry_source_frame.id'], name=op.f('fk_silver_smr_telemetry_frame_id_telemetry_source_frame'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_silver_smr_telemetry')),
    sa.UniqueConstraint('charger_id', 'smr_id', 'event_time', 'frame_sequence', name='uq_silver_smr_telemetry')
    )
    op.create_index(op.f('ix_silver_smr_telemetry_charger_id'), 'silver_smr_telemetry', ['charger_id'], unique=False)
    op.create_index(op.f('ix_silver_smr_telemetry_event_time'), 'silver_smr_telemetry', ['event_time'], unique=False)
    op.create_index(op.f('ix_silver_smr_telemetry_frame_id'), 'silver_smr_telemetry', ['frame_id'], unique=False)
    op.create_index('ix_silver_smr_telemetry_lookup', 'silver_smr_telemetry', ['charger_id', 'smr_id', 'event_time', 'frame_sequence'], unique=False)
    op.create_index(op.f('ix_silver_smr_telemetry_smr_id'), 'silver_smr_telemetry', ['smr_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_silver_smr_telemetry_smr_id'), table_name='silver_smr_telemetry')
    op.drop_index('ix_silver_smr_telemetry_lookup', table_name='silver_smr_telemetry')
    op.drop_index(op.f('ix_silver_smr_telemetry_frame_id'), table_name='silver_smr_telemetry')
    op.drop_index(op.f('ix_silver_smr_telemetry_event_time'), table_name='silver_smr_telemetry')
    op.drop_index(op.f('ix_silver_smr_telemetry_charger_id'), table_name='silver_smr_telemetry')
    op.drop_table('silver_smr_telemetry')
    op.drop_index(op.f('ix_silver_site_metadata_frame_id'), table_name='silver_site_metadata')
    op.drop_index(op.f('ix_silver_site_metadata_event_time'), table_name='silver_site_metadata')
    op.drop_index(op.f('ix_silver_site_metadata_charger_id'), table_name='silver_site_metadata')
    op.drop_table('silver_site_metadata')
    op.drop_index('ix_silver_session_observation_lookup', table_name='silver_session_observation')
    op.drop_index(op.f('ix_silver_session_observation_frame_id'), table_name='silver_session_observation')
    op.drop_index(op.f('ix_silver_session_observation_event_time'), table_name='silver_session_observation')
    op.drop_index(op.f('ix_silver_session_observation_connector_id'), table_name='silver_session_observation')
    op.drop_index(op.f('ix_silver_session_observation_charger_id'), table_name='silver_session_observation')
    op.drop_table('silver_session_observation')
    op.drop_index(op.f('ix_silver_rectifier_telemetry_rectifier_id'), table_name='silver_rectifier_telemetry')
    op.drop_index('ix_silver_rectifier_telemetry_lookup', table_name='silver_rectifier_telemetry')
    op.drop_index(op.f('ix_silver_rectifier_telemetry_frame_id'), table_name='silver_rectifier_telemetry')
    op.drop_index(op.f('ix_silver_rectifier_telemetry_event_time'), table_name='silver_rectifier_telemetry')
    op.drop_index(op.f('ix_silver_rectifier_telemetry_charger_id'), table_name='silver_rectifier_telemetry')
    op.drop_table('silver_rectifier_telemetry')
    op.drop_index('ix_silver_provenance_record', table_name='silver_observation_provenance')
    op.drop_index('ix_silver_provenance_frame', table_name='silver_observation_provenance')
    op.drop_index(op.f('ix_silver_observation_provenance_source_file_id'), table_name='silver_observation_provenance')
    op.drop_index(op.f('ix_silver_observation_provenance_silver_table_name'), table_name='silver_observation_provenance')
    op.drop_index(op.f('ix_silver_observation_provenance_silver_record_id'), table_name='silver_observation_provenance')
    op.drop_index(op.f('ix_silver_observation_provenance_frame_id'), table_name='silver_observation_provenance')
    op.drop_index(op.f('ix_silver_observation_provenance_bronze_row_id'), table_name='silver_observation_provenance')
    op.drop_table('silver_observation_provenance')
    op.drop_index(op.f('ix_silver_normalization_run_file_id'), table_name='silver_normalization_run')
    op.drop_table('silver_normalization_run')
    op.drop_index('ix_silver_lifecycle_counter_observation_lookup', table_name='silver_lifecycle_counter_observation')
    op.drop_index(op.f('ix_silver_lifecycle_counter_observation_frame_id'), table_name='silver_lifecycle_counter_observation')
    op.drop_index(op.f('ix_silver_lifecycle_counter_observation_event_time'), table_name='silver_lifecycle_counter_observation')
    op.drop_index(op.f('ix_silver_lifecycle_counter_observation_charger_id'), table_name='silver_lifecycle_counter_observation')
    op.drop_table('silver_lifecycle_counter_observation')
    op.drop_index('ix_silver_contactor_observation_lookup', table_name='silver_contactor_observation')
    op.drop_index(op.f('ix_silver_contactor_observation_frame_id'), table_name='silver_contactor_observation')
    op.drop_index(op.f('ix_silver_contactor_observation_event_time'), table_name='silver_contactor_observation')
    op.drop_index(op.f('ix_silver_contactor_observation_charger_id'), table_name='silver_contactor_observation')
    op.drop_table('silver_contactor_observation')
    op.drop_index('ix_silver_connector_telemetry_lookup', table_name='silver_connector_telemetry')
    op.drop_index(op.f('ix_silver_connector_telemetry_frame_id'), table_name='silver_connector_telemetry')
    op.drop_index(op.f('ix_silver_connector_telemetry_event_time'), table_name='silver_connector_telemetry')
    op.drop_index(op.f('ix_silver_connector_telemetry_connector_id'), table_name='silver_connector_telemetry')
    op.drop_index(op.f('ix_silver_connector_telemetry_charger_id'), table_name='silver_connector_telemetry')
    op.drop_table('silver_connector_telemetry')
    op.drop_index('ix_silver_configuration_snapshot_lookup', table_name='silver_configuration_snapshot')
    op.drop_index(op.f('ix_silver_configuration_snapshot_frame_id'), table_name='silver_configuration_snapshot')
    op.drop_index(op.f('ix_silver_configuration_snapshot_event_time'), table_name='silver_configuration_snapshot')
    op.drop_index(op.f('ix_silver_configuration_snapshot_config_hash'), table_name='silver_configuration_snapshot')
    op.drop_index(op.f('ix_silver_configuration_snapshot_charger_id'), table_name='silver_configuration_snapshot')
    op.drop_table('silver_configuration_snapshot')
    op.drop_index('ix_silver_communication_observation_lookup', table_name='silver_communication_observation')
    op.drop_index(op.f('ix_silver_communication_observation_frame_id'), table_name='silver_communication_observation')
    op.drop_index(op.f('ix_silver_communication_observation_event_time'), table_name='silver_communication_observation')
    op.drop_index(op.f('ix_silver_communication_observation_charger_id'), table_name='silver_communication_observation')
    op.drop_table('silver_communication_observation')
    op.drop_index('ix_silver_charger_telemetry_lookup', table_name='silver_charger_telemetry')
    op.drop_index(op.f('ix_silver_charger_telemetry_frame_id'), table_name='silver_charger_telemetry')
    op.drop_index(op.f('ix_silver_charger_telemetry_event_time'), table_name='silver_charger_telemetry')
    op.drop_index(op.f('ix_silver_charger_telemetry_charger_id'), table_name='silver_charger_telemetry')
    op.drop_table('silver_charger_telemetry')
    op.drop_index('ix_silver_alarm_observation_lookup', table_name='silver_alarm_observation')
    op.drop_index(op.f('ix_silver_alarm_observation_frame_id'), table_name='silver_alarm_observation')
    op.drop_index(op.f('ix_silver_alarm_observation_event_time'), table_name='silver_alarm_observation')
    op.drop_index(op.f('ix_silver_alarm_observation_charger_id'), table_name='silver_alarm_observation')
    op.drop_table('silver_alarm_observation')
    # ### end Alembic commands ###
